### ISSUE TITLE
ethers.getDefaultProvider is not working

### ISSUE THREAD

**Issue by ricmoo** [ethers-io/ethers-aion#3]
The ethers.getDefaultProvider is throwing an error:

```javascript
> aion.getDefaultProvider("mastery")
Thrown:
Error: unsupported network (argument="network", value={"name":"ropsten","chainId":3,"ensAddress":"0x112234455c3a32fd11230c42e7bccd4a84e02010"}, version=@TODO)
    at makeError (/private/tmp/test-aion/node_modules/@ethersproject/errors/index.js:109:17)
    at throwError (/private/tmp/test-aion/node_modules/@ethersproject/errors/index.js:120:11)
    at Object.throwArgumentError (/private/tmp/test-aion/node_modules/@ethersproject/errors/index.js:124:12)
    at Function.NodesmithProvider.getUrl (/private/tmp/test-aion/node_modules/@ethersproject-aion/providers/nodesmith-provider.js:43:23)
    at NodesmithProvider.UrlJsonRpcProvider [as constructor] (/private/tmp/test-aion/node_modules/@ethersproject/providers/url-json-rpc-provider.js:36:30)
    at NodesmithProvider.UrlJsonRpcProvider [as constructor] (/private/tmp/test-aion/node_modules/@ethersproject-aion/providers/url-json-rpc-provider.js:22:42)
    at new NodesmithProvider (/private/tmp/test-aion/node_modules/@ethersproject-aion/providers/nodesmith-provider.js:29:42)
    at Object._defaultProvider (/private/tmp/test-aion/node_modules/@ethersproject-aion/networks/index.js:7:20)
    at Object.getDefaultProvider (/private/tmp/test-aion/node_modules/@ethersproject-aion/ethers/aion.js:43:14) {
  reason: 'unsupported network',
  code: 'INVALID_ARGUMENT',
  argument: 'network',
  value: {
    name: 'ropsten',
    chainId: 3,
    ensAddress: '0x112234455c3a32fd11230c42e7bccd4a84e02010',
    _defaultProvider: [Function]
  }
}
> aion.getDefaultProvider("")
Thrown:
Error: unsupported getDefaultProvider network (operation="getDefaultProvider", network="", version=@TODO)
    at makeError (/private/tmp/test-aion/node_modules/@ethersproject/errors/index.js:109:17)
    at Object.throwError (/private/tmp/test-aion/node_modules/@ethersproject/errors/index.js:120:11)
    at Object.getDefaultProvider (/private/tmp/test-aion/node_modules/@ethersproject-aion/ethers/aion.js:38:16) {
  reason: 'unsupported getDefaultProvider network',
  code: 'UNSUPPORTED_OPERATION',
  operation: 'getDefaultProvider',
  network: ''
}
```

**Comment by ricmoo** [comment]
Fixed in `5.0.0-beta.138`.
